# Generated by Django 3.1.1 on 2021-05-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mikrotik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('host', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('port_api', models.IntegerField(default=8728)),
                ('port_http', models.IntegerField(default=80)),
                ('datetime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('ide', models.CharField(max_length=20)),
                ('tipeide', models.CharField(max_length=5)),
                ('mk_id', models.IntegerField(default=0)),
                ('useraddress', models.CharField(max_length=150)),
                ('ipaddress', models.CharField(max_length=15)),
                ('macaddress', models.CharField(max_length=12)),
                ('updo_plan', models.CharField(default='1M/1M', max_length=9)),
                ('datetime', models.TimeField()),
            ],
        ),
    ]
