# Generated by Django 3.1.1 on 2021-06-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotik',
            name='datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime',
            field=models.DateField(),
        ),
    ]
