# Generated by Django 3.1.1 on 2021-06-01 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210601_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mikrotik',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='datetime',
        ),
        migrations.AddField(
            model_name='mikrotik',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 13, 52, 39, 352530)),
        ),
        migrations.AddField(
            model_name='mikrotik',
            name='datetime_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 13, 52, 39, 352530)),
        ),
        migrations.AddField(
            model_name='user',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 13, 52, 39, 351543)),
        ),
        migrations.AddField(
            model_name='user',
            name='datetime_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 13, 52, 39, 351543)),
        ),
    ]
