# Generated by Django 3.1.1 on 2021-06-01 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210601_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotik',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mikrotik',
            name='datetime_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 14, 26, 21, 167860)),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 14, 26, 21, 166433)),
        ),
    ]
