# Generated by Django 3.1.1 on 2021-06-02 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210601_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mk_interface',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mikrotik',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 46, 25, 562239)),
        ),
        migrations.AlterField(
            model_name='mikrotik',
            name='datetime_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 46, 25, 562239)),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 46, 25, 561207)),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 46, 25, 561207)),
        ),
    ]
