# Generated by Django 3.1.1 on 2021-06-02 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210601_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotik',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 47, 37, 214410)),
        ),
        migrations.AlterField(
            model_name='mikrotik',
            name='datetime_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 47, 37, 214410)),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 47, 37, 213413)),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 47, 37, 214410)),
        ),
    ]
