# Generated by Django 3.1.1 on 2021-06-02 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210601_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mk_disabled',
            field=models.CharField(default='false', max_length=5),
        ),
        migrations.AlterField(
            model_name='mikrotik',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 49, 39, 249480)),
        ),
        migrations.AlterField(
            model_name='mikrotik',
            name='datetime_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 49, 39, 249480)),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 49, 39, 248449)),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime_edit',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 19, 49, 39, 248449)),
        ),
    ]
